version: '3'
services:
  balance:
    build: ./balance
    platform: linux/amd64
    container_name: balance
    volumes:
      - ./balance:/app
    ports:
      - "3003:3003"
    depends_on:
      - mysql
      - rabbitmq

  walletcore:
    build: ./WalletCore
    platform: linux/amd64
    container_name: walletcore
    volumes:
      - ./WalletCore:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_wallet:/var/lib/mysql
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_wallet:

